url: https://dominickta.com
 #baseurl: /agency-jekyll-theme/

# Site settings
title: Dom's Husky Experience
email: dom@dominickta.com
description: "Learn more about Dom's Husky experience!"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/dominickta/
  - title: github
    url: https://github.com/dominickta/
  - title: instagram
    url: https://instagram.com/yumhojiat

# Build settings
markdown: kramdown
permalink: pretty
